version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    restart: "always"
