name: Deploy Frontend with Docker to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file with Vite secrets
        run: |
          echo "VITE_VAPID_KEY=${{ secrets.VITE_VAPID_KEY }}" >> .env
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" >> .env

      - name: Build Docker image
        run: docker build -t frontend-app .

      - name: Extract static files from Docker container
        run: |
          CONTAINER_ID=$(docker create frontend-app)
          docker cp $CONTAINER_ID:/usr/share/nginx/html ./dist
          docker rm $CONTAINER_ID

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./dist"
